trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:

# 🔹 Set Java version
- task: JavaToolInstaller@0
  inputs:
    versionSpec: '17'
    jdkArchitectureOption: 'x64'
    jdkSourceOption: 'PreInstalled'

# 🔹 Build Spring Boot project
- task: Maven@4
  inputs:
    mavenPomFile: 'pom.xml'
    goals: 'clean package'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.17'

- script: |
    echo "Build successful"
  displayName: "Build Stage"